#!/bin/sh

SESSION_NAME="sixdee-vpn"
VPN_CONFIG="$HOME/.config/.vpn/samin.tejas__ssl_vpn_config.ovpn"
OPTION=$(echo -e "Connect\nOpen\nClose" | rofi -dmenu -p "6D VPN")


kill_vpn_session() {
  tmux send-keys -t $SESSION_NAME C-c
  sleep 2
  tmux kill-session -t $SESSION_NAME
}

is_session_active() {
  tmux has-session -t $SESSION_NAME 2>/dev/null
}

case "$OPTION" in
  "Connect")
    if is_session_active; then
      echo "VPN session is already active."
    else
      tmux new-session -s $SESSION_NAME "sudo openvpn --config $VPN_CONFIG"
    fi
    ;;
  "Open")
    if is_session_active; then
      tmux attach-session -t $SESSION_NAME
    else
      echo "VPN session is not active."
    fi
    ;;
  "Close")
    if is_session_active; then
      kill_vpn_session
      echo "VPN session killed."
    else
      echo "VPN session is not active."
    fi
    ;;
  *)
    echo "Invalid option selected."
    ;;
esac
