#!/bin/sh

menu1="Shutdown\nReboot"

option=$(echo -e $menu1 | rofi -dmenu -i -p ' ' -theme-str 'listview { lines: 2; }')

if [ "$option" == "Shutdown" ];
then
	shutdown now
elif [ "$option" == "Reboot" ];
then 
	reboot
else echo "Not a valid powerctl command"
fi

